import streamlit as st

st.write('<!DOCTYPE html>')
st.write('<html lang="en">')
st.write('<head>')
st.write('  <meta charset="UTF-8">')
st.write('  <title>KBD</title>')
st.write('  <style>')
st.write('    /* CSS 스타일링 코드를 여기에 입력하세요 */')
st.write('  </style>')
st.write('</head>')
st.write('<body>')
st.write('  <header>')
st.write('    <h1>Korea Baseball Data</h1>')
st.write('  </header>')
st.write('  <div class="container">')
st.write('    <form>')
st.write('      <!-- 폼 및 선택 옵션을 여기에 입력하세요 -->')
st.write('    </form>')
st.write('    <button onclick="location.href=\'page3.html\'">검색</button>')
st.write('    <div class="info">')
st.write('      <!-- 정보 섹션을 여기에 입력하세요 -->')
st.write('    </div>')
st.write('  </div>')
st.write('</body>')
st.write('</html>')

